Repository Techeer-AndYou/frontend, pull requests merged in 2023-11, with the labels that each got.

#28 Design/7 온보딩페이지 디자인다듬기
  .gitmessage.txt
  package-lock.json
  package.json
  src/app/(user)/login/page.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/signup/page.tsx
  src/app/api/v1/users/login/route.ts
  yarn.lock
Labels: Feature, Refactor

#30 Refactor/29 start onboard page
  src/app/(info)/main/page.tsx
  src/app/(info)/onboard/page.tsx
  src/app/(user)/addfriends/page.tsx
  src/app/page.tsx
  src/components/global/Header.tsx
  src/components/global/Logo.tsx
  src/components/relation/Relation/Relation.tsx
  src/utils/animations.ts
  yarn.lock
Labels: Refactor

#33 refactor: startpage 다듬기
  src/app/page.tsx
  src/components/global/Logo.tsx
  src/components/three/NightSky/NightSky.tsx
  src/components/three/NightSky/createUIElements.ts
Labels: Feature, SELF-MERGED
