Repository Techeer-AndYou/frontend, pull requests merged in 2023-10, with the labels that each got.

#13 Design/11 relationshippage migration
  .eslintrc.js
  package-lock.json
  package.json
  public/images/ad.png
  public/images/final_ad.png
  public/images/remember_plus_background.gif
  public/images/techeer_ad.png
  src/app/(info)/onboard/page.tsx
  src/app/(user)/relation/page.tsx
  src/app/globals.css
  src/components/relation/CardDetail.tsx
  src/components/relation/CardInfo.tsx
  src/components/relation/Chart/Chart.tsx
  src/components/relation/Chart/ChartContent.tsx
  src/components/relation/Relation/Relation.tsx
  src/components/relation/Relation/RelationGraph.tsx
  src/components/relation/RelationModal.tsx
  src/components/relation/Sky.tsx
  src/components/relation/ZoomableSVG.tsx
  src/components/relation/mockData.ts
  src/components/relation/modals/CardInfoUpdateModal.tsx
  src/components/relation/modals/CardPhotoUpdateModal.tsx
  src/components/relation/modals/CardShowModal.tsx
  src/components/relation/services/fetchRelations.ts
  src/components/relation/types.ts
  src/components/relation/utils/domain.ts
  yarn.lock
Labels: Design, Feature, Refactor, Chore

#12 Design/4 - 회원정보 페이지 마이그레이션
  package.json
  src/app/(user)/mypage/page.tsx
  src/app/globals.css
  src/components/analytic/BarChart.tsx
  src/components/analytic/LineChart.tsx
  src/components/analytic/PieChart.tsx
  src/components/card/CardInfo.tsx
  src/components/card/CardInfoUpdateModal.tsx
  src/components/card/CardPhotoUpdateModal.tsx
  src/components/common/CloseIcon.tsx
  src/components/user/UserInfoUpdateModal.tsx
  src/components/user/UserPhotoUpdateModal.tsx
  src/components/user/UserProfile.tsx
  src/domain/domain.ts
  yarn.lock
Labels: 높음, 진행 중, Design, Feature, Refactor

#14 Design/3 - 로그인/회원가입 페이지 퍼블리싱
  next.config.js
  package.json
  src/app/(user)/login/page.tsx
  src/app/(user)/signup/page.tsx
  src/assets/logo.png
  src/assets/logo.svg
  src/components/info/Onboard/Text.tsx
  yarn.lock
Labels: Docs, 질문, 높음, 진행 중, Design, Feature, Refactor

#18 Feature/16 relation page 다듬기
  public/images/RememberPlusV2.png
  src/components/global/SearchBar.tsx
  src/components/relation/Relation/Relation.tsx
  yarn.lock
Labels: Design

#22 feat: Header 모듈화
  src/app/(info)/main/page.tsx
  src/app/(user)/mypage/page.tsx
  src/components/global/Header.tsx
  yarn.lock
Labels: Feature, SELF-MERGED

#26 Design/27 온보딩페이지 및 로그인화면 다듬기
  src/components/info/Onboard/Charts.tsx
  src/components/info/Onboard/Information.tsx
  src/components/info/Onboard/Profile.tsx
  src/components/info/Onboard/Text.tsx
Labels: Design
